# -*- coding: utf-8 -*-
"""CS5530_HW1_Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-t0115eHGBdV0K5ntIF0DRZgLm8FX5W

# File Directory
"""

|-- students_performance_visualization/
|   |-- data/
│       |-- StudentsPerformance.csv
│       |-- README.txt
|   │-- src/
│       |-- CS5530_HW1_Q2.ipynb
|   │-- results/
│       |-- math_scores_by_lunch_type.png
│       |-- avg_scores_by_parental_education.png
│       |-- math_reading_scores_by_gender.png
│       |-- lunch_distribution_by_race.png
│       |-- reading_score_by_gender.png
|       |-- visualizations_analysis.txt

"""# Import libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""

# Mount Google Drive and Import File"""

from google.colab import drive
drive.mount('/content/drive')

data = pd.read_csv("/content/drive/MyDrive/StudentsPerformance.csv")
data.head()

data.shape

"""# Inspect Data
check for null values,
duplicates,
data types,
and unexpected values

"""

print(data.isnull().sum())

print(data.duplicated().sum())

print(data.dtypes)

for column in data.columns:
    print(f"{column}: {data[column].unique()}")

"""# Data Visualizations

1. The boxplot of math scores by lunch type shows how students with a standard lunch type tend to have a higher median math score compared to those with a free/reduced lunch type. We can see there is an outlier whose math score is significantly higher than the rest of the students with a free/reduced lunch type. In both lunch types, there exists outliers with significantly lower math scores.
"""

# 1. Boxplot of Math Scores by Lunch Type
plt.figure(figsize=(8, 6))
sns.boxplot(data, x="lunch", y="math score", hue="lunch")
plt.title('Math Score by Lunch Type')
plt.xlabel("Lunch")
plt.ylabel("Math Scores")
plt.savefig("math_scores_by_lunch_type.png", dpi=300, bbox_inches='tight')
plt.show()

"""2. The bar chart allows for visualizing average math, reading, and writing scores among students and their parents level of education. From the chart we can see students whose parents have a lower education level (high school, some high school, some college) tend to have slightly lower scores across the board compared with those whose parents have higher education levels (associate's, bachelor's, or master's degrees)."""

# 2. Bar Chart of Average Math, Reading, and Writing Scores by Level of Parental Education
ax = data.groupby("parental level of education")[["math score", "reading score", "writing score"]].mean().plot(kind="bar")
plt.title("Average Scores by Parental Education Level")
plt.xlabel("Parental Education Level")
plt.ylabel("Average Score")
plt.savefig("avg_scores_by_parental_education.png", dpi=300, bbox_inches='tight')
plt.show()

"""3. With the scatter plot we can see that there is a positive correlation between math and reading scores. As math scores increase, reading scores tend to increase. There are gender differences that can be seen as well. Females tend to have higher reading scores compared to males with similar math scores. We can see some outliers exist that have lower scores in either math or reading."""

# 3. Scatter Plot of Math and Reading Scores by Gender
sns.scatterplot(data=data, x='math score', y='reading score', hue='gender')
plt.title('Scatter Plot of Math and Reading Scores by Gender')
plt.savefig("math_reading_scores_by_gender.png", dpi=300, bbox_inches='tight')
plt.show()

"""4. In the stacked bar chart we can see the frequency of lunch types among the different race/ethnicity groups. Groups C and D have the largest student counts and as well as the larger absolute count of students who receive free/reduced lunch as well as students who receive the standard lunch. Group A has the fewest students as well as the fewest students receiving free/reduced lunch. From this chart we can also see the majority of students are receiving the standard lunch among all groups."""

# 4. Stacked Bar Chart Distribution of Lunch Type by Race
race_lunch_counts = data.groupby(["race/ethnicity", "lunch"]).size().unstack()
race_lunch_counts.plot(kind="bar", stacked=True, colormap="viridis")
plt.title("Lunch Distribution by Race")
plt.xlabel("Race/Ethnicity")
plt.ylabel("Count")
plt.legend(title="Lunch")
plt.savefig("lunch_distribution_by_race.png", dpi=300, bbox_inches='tight')
plt.show()

"""5. In this violin plot we can visualize the gender differences in male and female students reading scores. We can see that females tend to have an overall higher median score compared to their counterparts. Female students have a wider range of scores, with their lowest scores being lower than those of male students."""

# 5. Violinplot of Reading Score by Gender
plt.figure(figsize=(8, 6))
sns.violinplot(data, x="gender", y="reading score", hue="gender")
plt.title('Reading Score by Gender')
plt.xlabel("Gender")
plt.ylabel("Reading Score")
plt.savefig("reading_score_by_gender.png", dpi=300, bbox_inches='tight')
plt.show()