# -*- coding: utf-8 -*-
"""CS5530_HW1_Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLNAkMIdDVIwZd6IkXjWOBxNoCCoOB2F

# Folder Structure
"""

|-- frailty_study/
|   │-- data_raw/
│       |-- frailty_data.csv
│       |-- README.txt
|   │-- data_clean/
│       |-- clean_frailty_data.csv
|   |-- src/
|       |-- clean_data.ipynb
|       |-- frailty_analysis.ipynb
|   │-- results/
│       |-- frailty_analysis.txt

"""# Three Stages of Reproducible Workflow for Frailty Study

Stage 1 Data Collection:

*   Collect data on "Height", "Weight", "Age", "Grip Strength", and "Frailty" from table
*   Store the raw data in CSV Format, such as "frailty_data.csv"
*   Document the data sources and the variables in a README.txt file
"""

|-- frailty_study/
|   │-- data_raw/
│       |-- frailty_data.csv
│       |-- README.txt

"""Stage 2 Data Processing/Cleaning:

* Familarize with the dataset
* Check for missing values, duplicates, outliers
*   Convert the categorical column "Frailty" to dummy variables like 0-No & 1-Yes
* Save cleaned data, clean_frailty_data.csv
  




"""

|-- frailty_study/
|   │-- data_clean/
│       |-- clean_frailty_data.csv
|   |-- src/
|       |-- clean_data.ipynb

"""Stage 3 Data Analysis:

*   Calculate statistics for numerical columns like the mean, median, and standard deviations
*   Perform correlative analyses like grip strength versus age, weight, and height.
* Create visualizations such as bar graphs, scatterplots, histograms to visualize the data
* Create files to store analysis results and visualizations


"""

|-- frailty_study/
|   │-- results/
│       |-- frailty_analysis.txt
|   |-- src/
|       |-- clean_data.ipynb
|       |-- frailty_analysis.ipynb